'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Logo } from '@/components/Logo';
import { Button, Card, Input } from '@/components/ui';
import { login, readableError, register } from '@/lib/api';

export function AuthForm({ mode }: { mode: 'login' | 'register' }) { const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); if (mode === 'register' && password !== confirm) { setError('两次输入的密码不一致。'); return; } setLoading(true); setError(''); try { if (mode === 'register') await register(email, password); else await login(email, password); router.replace('/dashboard'); } catch (err) { setError(readableError(err)); } finally { setLoading(false); } }; return <div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-md items-center px-4 py-12"><Card className="w-full p-6 sm:p-8"><Logo/><h1 className="mt-8 text-2xl font-bold">{mode === 'login' ? '登录你的工作台' : '创建公开测试账号'}</h1><p className="mt-2 text-sm text-muted-foreground">{mode === 'login' ? '继续查看任务、报告和用量。' : '当前产品仅用于小规模 B 站分析测试。'}</p><form className="mt-7 space-y-4" onSubmit={submit}><label className="block text-sm font-medium">邮箱<Input className="mt-2" type="email" required autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="block text-sm font-medium">密码<Input className="mt-2" type="password" required minLength={8} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="至少 8 位"/></label>{mode === 'register' && <label className="block text-sm font-medium">确认密码<Input className="mt-2" type="password" required minLength={8} autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)}/></label>}{error && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950 dark:text-red-200">{error}</div>}<Button className="w-full" size="lg" disabled={loading}>{loading ? '请稍候…' : mode === 'login' ? '登录' : '注册并进入工作台'}</Button></form><p className="mt-5 text-center text-sm text-muted-foreground">{mode === 'login' ? '还没有账号？' : '已有账号？'} <Link className="font-medium text-indigo-600 hover:underline dark:text-indigo-300" href={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? '注册' : '登录'}</Link></p></Card></div>; }
