"""create product mvp tables

Revision ID: 20260713_0001
Revises:
Create Date: 2026-07-13
"""
from alembic import op
import sqlalchemy as sa

revision = "20260713_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("users", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("hashed_password", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("email"))
    op.create_index("ix_users_email", "users", ["email"])
    op.create_table("analysis_jobs", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("user_id", sa.Uuid(), nullable=False), sa.Column("query", sa.Text(), nullable=False), sa.Column("platforms", sa.JSON(), nullable=False), sa.Column("analysis_mode", sa.String(20), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("progress", sa.Integer(), nullable=False), sa.Column("retry_count", sa.Integer(), nullable=False), sa.Column("idempotency_key", sa.String(128), nullable=False), sa.Column("arq_job_id", sa.String(180), nullable=True), sa.Column("error_code", sa.String(64), nullable=True), sa.Column("error_message", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=True), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True), sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("user_id", "idempotency_key", name="uq_job_user_idempotency"))
    op.create_index("ix_analysis_jobs_status", "analysis_jobs", ["status"]); op.create_index("ix_analysis_jobs_user_id", "analysis_jobs", ["user_id"]); op.create_index("ix_jobs_user_created", "analysis_jobs", ["user_id", "created_at"])
    op.create_table("reports", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("job_id", sa.Uuid(), nullable=False), sa.Column("user_id", sa.Uuid(), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("structured_claims", sa.JSON(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("model_info", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_reports_job_id", "reports", ["job_id"]); op.create_index("ix_reports_user_id", "reports", ["user_id"])
    op.create_table("evidence_items", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("evidence_id", sa.String(40), nullable=False), sa.Column("job_id", sa.Uuid(), nullable=False), sa.Column("report_id", sa.Uuid(), nullable=True), sa.Column("tool", sa.String(80), nullable=False), sa.Column("source_type", sa.String(80), nullable=False), sa.Column("title", sa.Text(), nullable=False), sa.Column("source_url", sa.Text(), nullable=True), sa.Column("platform", sa.String(32), nullable=False), sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False), sa.Column("raw_data", sa.JSON(), nullable=False), sa.Column("summary", sa.Text(), nullable=True), sa.Column("data_fields", sa.JSON(), nullable=False), sa.Column("transcript_segment", sa.JSON(), nullable=True), sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("job_id", "evidence_id", name="uq_evidence_job_id"))
    op.create_index("ix_evidence_items_evidence_id", "evidence_items", ["evidence_id"]); op.create_index("ix_evidence_items_job_id", "evidence_items", ["job_id"]); op.create_index("ix_evidence_items_report_id", "evidence_items", ["report_id"])
    op.create_table("job_events", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("job_id", sa.Uuid(), nullable=False), sa.Column("event_type", sa.String(40), nullable=False), sa.Column("message", sa.String(300), nullable=False), sa.Column("progress", sa.Integer(), nullable=False), sa.Column("level", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id")); op.create_index("ix_job_events_job_id", "job_events", ["job_id"])
    op.create_table("report_feedback", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("report_id", sa.Uuid(), nullable=False), sa.Column("user_id", sa.Uuid(), nullable=False), sa.Column("rating", sa.Integer(), nullable=False), sa.Column("useful", sa.Boolean(), nullable=False), sa.Column("reason", sa.String(100), nullable=False), sa.Column("comment", sa.Text(), nullable=False), sa.Column("adopted", sa.Boolean(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id")); op.create_index("ix_report_feedback_report_id", "report_feedback", ["report_id"]); op.create_index("ix_report_feedback_user_id", "report_feedback", ["user_id"])
    op.create_table("usage_records", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("user_id", sa.Uuid(), nullable=False), sa.Column("job_id", sa.Uuid(), nullable=False), sa.Column("input_tokens", sa.Integer(), nullable=False), sa.Column("output_tokens", sa.Integer(), nullable=False), sa.Column("estimated_cost", sa.Float(), nullable=False), sa.Column("asr_seconds", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("job_id")); op.create_index("ix_usage_records_user_id", "usage_records", ["user_id"])
    op.create_table("share_links", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("report_id", sa.Uuid(), nullable=False), sa.Column("user_id", sa.Uuid(), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("token_hash")); op.create_index("ix_share_links_report_id", "share_links", ["report_id"]); op.create_index("ix_share_links_token_hash", "share_links", ["token_hash"]); op.create_index("ix_share_links_user_id", "share_links", ["user_id"])


def downgrade() -> None:
    for table in ["share_links", "usage_records", "report_feedback", "job_events", "evidence_items", "reports", "analysis_jobs", "users"]:
        op.drop_table(table)
