'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { JobSummaryCard, UsageCard } from '@/components/product';
import { Button, Card, EmptyState, ErrorState, LoadingState } from '@/components/ui';
import { getUsage, listJobs, readableError, type Job, type UsageSummary } from '@/lib/api';

export default function DashboardPage() { const [jobs, setJobs] = useState<Job[]>([]); const [usage, setUsage] = useState<UsageSummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { Promise.all([listJobs('?limit=5'), getUsage()]).then(([jobData, usageData]) => { setJobs(jobData.items); setUsage(usageData); }).catch((err) => setError(readableError(err))).finally(() => setLoading(false)); }, []); return <AppShell><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Dashboard</p><h1 className="mt-1 text-2xl font-bold">你的 B 站分析工作台</h1></div><Link href="/jobs/new"><Button>新建分析</Button></Link></div>{loading ? <LoadingState/> : error ? <ErrorState description={error}/> : <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">最近任务</h2><Link href="/history" className="text-sm text-indigo-600 hover:underline dark:text-indigo-300">查看全部</Link></div><div className="space-y-3">{jobs.length ? jobs.map((job) => <JobSummaryCard key={job.id} id={job.id} title={job.query} status={job.status} progress={job.progress} createdAt={job.created_at}/>) : <Card><EmptyState title="还没有分析任务" description="从一个赛道、选题或竞品问题开始。" action={<Link href="/jobs/new"><Button>创建第一个任务</Button></Link>}/></Card>}</div></section><aside className="space-y-4">{usage && <UsageCard usage={usage}/>}<Card className="p-5"><h2 className="font-semibold">快捷模板</h2>{['B站赛道爆款分析','竞品账号内容拆解','热门标题结构分析','选题方向分析'].map((item) => <Link key={item} href={`/jobs/new?template=${encodeURIComponent(item)}`} className="mt-3 block rounded-xl border p-3 text-sm hover:border-indigo-300 hover:bg-indigo-50/40 dark:hover:bg-indigo-950/20">{item}</Link>)}</Card></aside></div>}</AppShell>; }
